/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Resolution = IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat });
export const Time = IDL.Int;
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'resolution' : Resolution,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
  'listPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'savePhoto' : IDL.Func([IDL.Text, Resolution, ExternalBlob], [IDL.Text], []),
  'searchPhotos' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Resolution = IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat });
  const Time = IDL.Int;
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'resolution' : Resolution,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
    'listPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'savePhoto' : IDL.Func(
        [IDL.Text, Resolution, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'searchPhotos' : IDL.Func([IDL.Text], [IDL.Vec(Photo)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };